# Code Generated by Sidekick is for learning and experimentation purposes only.
resource "aws_cloudwatch_log_group" "ecs_app" {
  name              = "/ecs/my-first-task"
  retention_in_days = 7
}

resource "aws_ecs_task_definition" "my_first_task" {
  family                   = "my-first-task"
  requires_compatibilities = ["EC2"]
  network_mode             = "bridge"
  cpu                      = "128"
  memory                   = "256"
  execution_role_arn       = aws_iam_role.ecsTaskExecutionRole.arn

  container_definitions = jsonencode([
    {
      name      = "my-first-task"
      image     = "nginx:alpine"
      essential = true
      cpu       = 128
      memory    = 256

      portMappings = [
        {
          containerPort = 80
          hostPort      = 80
          protocol      = "tcp"
        }
      ]

      logConfiguration = {
        logDriver = "awslogs"
        options = {
          awslogs-group         = aws_cloudwatch_log_group.ecs_app.name
          awslogs-region        = "ap-south-1"
          awslogs-stream-prefix = "ecs"
        }
      }
    }
  ])
}
